# Generated by Django 5.0.1 on 2024-01-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donationevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='donationevent',
            name='recipients',
        ),
        migrations.AddField(
            model_name='donationevent',
            name='acceptors',
            field=models.ManyToManyField(blank=True, related_name='accepted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='donationevent',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('availability_for_donation', models.BooleanField(default=True)),
                ('bloodgroup', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
