# Generated by Django 5.0.1 on 2024-01-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_remove_donationevent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationevent',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.donationevent'),
        ),
    ]
