# Generated by Django 5.0.1 on 2024-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_donationevent_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='is_get_blood',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
